# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :beta do
    # sync_code_signing(type: "appstore")    # see code signing guide for more information
    increment_build_number(xcodeproj: "Niceter.xcodeproj")
    build_app(workspace: "Niceter.xcworkspace", scheme: "Niceter")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    # slack(message: "Successfully distributed a new beta build")
  end
end
